'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Feedback from "@/components/Feedback"; // <-- Import Feedback
import { Toaster } from "react-hot-toast";
import React, { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [showFeedback, setShowFeedback] = useState(false);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster position="top-center"/>
        <Navbar/>
        {children}
        <Footer/>
        {/* Floating Feedback Button */}
        <button
          className="fixed bottom-6 right-6 z-[200] bg-gradient-to-r from-orange-500 to-red-600 hover:from-orange-600 hover:to-red-700 text-white rounded-full shadow-lg p-4 flex items-center justify-center transition"
          onClick={() => setShowFeedback(true)}
          aria-label="Open Feedback"
        >
          <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" d="M8 10h.01M12 10h.01M16 10h.01M21 12c0 4.418-4.03 8-9 8a9.77 9.77 0 01-4-.8L3 21l1.8-4A7.97 7.97 0 013 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
          </svg>
        </button>
        {/* Feedback Modal */}
        {showFeedback && (
          <div className="fixed inset-0 z-[201] flex items-center justify-center bg-black/60">
            <div className="relative w-full max-w-md mx-auto">
              <button
                className="absolute top-2 right-2 text-orange-400 bg-slate-900/80 rounded-full p-2 hover:bg-slate-800 transition"
                onClick={() => setShowFeedback(false)}
                aria-label="Close Feedback"
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
              <Feedback />
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
